name: krish.yml

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "kraken"

          replace: "d3vilkrish"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Things'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: D3KRISH
          commit_user_email: legendmaster0535@gmail.com
